# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@fortawesome/fontawesome-free-5.12.0" = {
      name = "_at_fortawesome_slash_fontawesome-free";
      packageName = "@fortawesome/fontawesome-free";
      version = "5.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.12.0.tgz";
        sha512 = "vKDJUuE2GAdBERaQWmmtsciAMzjwNrROXA5KTGSZvayAsmuTGjam5z6QNqNPCwDfVljLWuov1nEC3mEQf/n6fQ==";
      };
    };
    "@types/q-1.5.2" = {
      name = "_at_types_slash_q";
      packageName = "@types/q";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/q/-/q-1.5.2.tgz";
        sha512 = "ce5d3q03Ex0sy4R14722Rmt6MT07Ua+k4FwDfdcToYJcMKNtRVQvJ6JCAPdAmAnbRb6CsX6aYb9m96NGod9uTw==";
      };
    };
    "alphanum-sort-1.0.2" = {
      name = "alphanum-sort";
      packageName = "alphanum-sort";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/alphanum-sort/-/alphanum-sort-1.0.2.tgz";
        sha1 = "97a1119649b211ad33691d9f9f486a8ec9fbe0a3";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "bootstrap-4.4.1" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-4.4.1.tgz";
        sha512 = "tbx5cHubwE6e2ZG7nqM3g/FZ5PQEDMWmMGNrCUBVRPHXTJaH7CBDdsLeu3eCh3B1tzAxTnAbtmrzvWEvT2NNEA==";
      };
    };
    "browserslist-4.8.3" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.8.3.tgz";
        sha512 = "iU43cMMknxG1ClEZ2MDKeonKE1CCrFVkQK2AqO2YWFmvIrx4JWrvQ4w4hQez6EpVI8rHTtqh/ruHHDHSOKxvUg==";
      };
    };
    "caller-callsite-2.0.0" = {
      name = "caller-callsite";
      packageName = "caller-callsite";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-callsite/-/caller-callsite-2.0.0.tgz";
        sha1 = "847e0fce0a223750a9a027c54b33731ad3154134";
      };
    };
    "caller-path-2.0.0" = {
      name = "caller-path";
      packageName = "caller-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-path/-/caller-path-2.0.0.tgz";
        sha1 = "468f83044e369ab2010fac5f06ceee15bb2cb1f4";
      };
    };
    "callsites-2.0.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-2.0.0.tgz";
        sha1 = "06eb84f00eea413da86affefacbffb36093b3c50";
      };
    };
    "caniuse-api-3.0.0" = {
      name = "caniuse-api";
      packageName = "caniuse-api";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-api/-/caniuse-api-3.0.0.tgz";
        sha512 = "bsTwuIg/BZZK/vreVTYYbSWoe2F+71P7K5QGEX+pT250DZbfU1MQ5prOKpPR+LL6uWKK3KMwMCAS74QB3Um1uw==";
      };
    };
    "caniuse-lite-1.0.30001021" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001021";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001021.tgz";
        sha512 = "wuMhT7/hwkgd8gldgp2jcrUjOU9RXJ4XxGumQeOsUr91l3WwmM68Cpa/ymCnWEDqakwFXhuDQbaKNHXBPgeE9g==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "coa-2.0.2" = {
      name = "coa";
      packageName = "coa";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/coa/-/coa-2.0.2.tgz";
        sha512 = "q5/jG+YQnSy4nRTV4F7lPepBJZ8qBNJJDBuJdoejDyLXgmL7IEo+Le2JDZudFTFt7mrCqIRaSjws4ygRCTCAXA==";
      };
    };
    "color-3.1.2" = {
      name = "color";
      packageName = "color";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color/-/color-3.1.2.tgz";
        sha512 = "vXTJhHebByxZn3lDvDJYw4lR5+uB3vuoHsuYA5AKuxRVn5wzzIfQKGLBmgdVRHKTJYeK5rvJcHnrd0Li49CFpg==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-string-1.5.3" = {
      name = "color-string";
      packageName = "color-string";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-string/-/color-string-1.5.3.tgz";
        sha512 = "dC2C5qeWoYkxki5UAXapdjqO672AM4vZuPGRQfO8b5HKuKGBbKWpITyDYN7TOFKvRW7kOgAn3746clDBMDJyQw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "cosmiconfig-5.2.1" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-5.2.1.tgz";
        sha512 = "H65gsXo1SKjf8zmrJ67eJk8aIRKV5ff2D4uKZIBZShbhGSpEmsQOPW/SKMKYhSTrqR7ufy6RP69rPogdaPh/kA==";
      };
    };
    "css-color-names-0.0.4" = {
      name = "css-color-names";
      packageName = "css-color-names";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-color-names/-/css-color-names-0.0.4.tgz";
        sha1 = "808adc2e79cf84738069b646cb20ec27beb629e0";
      };
    };
    "css-declaration-sorter-4.0.1" = {
      name = "css-declaration-sorter";
      packageName = "css-declaration-sorter";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-declaration-sorter/-/css-declaration-sorter-4.0.1.tgz";
        sha512 = "BcxQSKTSEEQUftYpBVnsH4SF05NTuBokb19/sBt6asXGKZ/6VP7PLG1CBCkFDYOnhXhPh0jMhO6xZ71oYHXHBA==";
      };
    };
    "css-select-2.1.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-2.1.0.tgz";
        sha512 = "Dqk7LQKpwLoH3VovzZnkzegqNSuAziQyNZUcrdDM401iY+R5NkGBXGmtO05/yaXQziALuPogeG0b7UAgjnTJTQ==";
      };
    };
    "css-select-base-adapter-0.1.1" = {
      name = "css-select-base-adapter";
      packageName = "css-select-base-adapter";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select-base-adapter/-/css-select-base-adapter-0.1.1.tgz";
        sha512 = "jQVeeRG70QI08vSTwf1jHxp74JoZsr2XSgETae8/xC8ovSnL2WF87GTLO86Sbwdt2lK4Umg4HnnwMO4YF3Ce7w==";
      };
    };
    "css-tree-1.0.0-alpha.37" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.0.0-alpha.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.0.0-alpha.37.tgz";
        sha512 = "DMxWJg0rnz7UgxKT0Q1HU/L9BeJI0M6ksor0OgqOnF+aRCDWg/N2641HmVyU9KVIu0OVVWOb2IpC9A+BJRnejg==";
      };
    };
    "css-unit-converter-1.1.1" = {
      name = "css-unit-converter";
      packageName = "css-unit-converter";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-unit-converter/-/css-unit-converter-1.1.1.tgz";
        sha1 = "d9b9281adcfd8ced935bdbaba83786897f64e996";
      };
    };
    "css-what-3.2.1" = {
      name = "css-what";
      packageName = "css-what";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-3.2.1.tgz";
        sha512 = "WwOrosiQTvyms+Ti5ZC5vGEK0Vod3FTt1ca+payZqvKuGJF+dq7bG63DstxtN0dpm6FxY27a/zS3Wten+gEtGw==";
      };
    };
    "cssesc-2.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-2.0.0.tgz";
        sha512 = "MsCAG1z9lPdoO/IUMLSBWBSVxVtJ1395VGIQ+Fc2gNdkQ1hNDnQdw3YhA71WJCBW1vdwA0cAnk/DnW6bqoEUYg==";
      };
    };
    "cssnano-4.1.10" = {
      name = "cssnano";
      packageName = "cssnano";
      version = "4.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano/-/cssnano-4.1.10.tgz";
        sha512 = "5wny+F6H4/8RgNlaqab4ktc3e0/blKutmq8yNlBFXA//nSFFAqAngjNVRzUvCgYROULmZZUoosL/KSoZo5aUaQ==";
      };
    };
    "cssnano-preset-default-4.0.7" = {
      name = "cssnano-preset-default";
      packageName = "cssnano-preset-default";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-4.0.7.tgz";
        sha512 = "x0YHHx2h6p0fCl1zY9L9roD7rnlltugGu7zXSKQx6k2rYw0Hi3IqxcoAGF7u9Q5w1nt7vK0ulxV8Lo+EvllGsA==";
      };
    };
    "cssnano-util-get-arguments-4.0.0" = {
      name = "cssnano-util-get-arguments";
      packageName = "cssnano-util-get-arguments";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-get-arguments/-/cssnano-util-get-arguments-4.0.0.tgz";
        sha1 = "ed3a08299f21d75741b20f3b81f194ed49cc150f";
      };
    };
    "cssnano-util-get-match-4.0.0" = {
      name = "cssnano-util-get-match";
      packageName = "cssnano-util-get-match";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-get-match/-/cssnano-util-get-match-4.0.0.tgz";
        sha1 = "c0e4ca07f5386bb17ec5e52250b4f5961365156d";
      };
    };
    "cssnano-util-raw-cache-4.0.1" = {
      name = "cssnano-util-raw-cache";
      packageName = "cssnano-util-raw-cache";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-raw-cache/-/cssnano-util-raw-cache-4.0.1.tgz";
        sha512 = "qLuYtWK2b2Dy55I8ZX3ky1Z16WYsx544Q0UWViebptpwn/xDBmog2TLg4f+DBMg1rJ6JDWtn96WHbOKDWt1WQA==";
      };
    };
    "cssnano-util-same-parent-4.0.1" = {
      name = "cssnano-util-same-parent";
      packageName = "cssnano-util-same-parent";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-same-parent/-/cssnano-util-same-parent-4.0.1.tgz";
        sha512 = "WcKx5OY+KoSIAxBW6UBBRay1U6vkYheCdjyVNDm85zt5K9mHoGOfsOsqIszfAqrQQFIIKgjh2+FDgIj/zsl21Q==";
      };
    };
    "csso-4.0.2" = {
      name = "csso";
      packageName = "csso";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/csso/-/csso-4.0.2.tgz";
        sha512 = "kS7/oeNVXkHWxby5tHVxlhjizRCSv8QdU7hB2FpdAibDU8FjTAolhNjKNTiLzXtUrKT6HwClE81yXwEk1309wg==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.0.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz";
        sha512 = "5HOHUDsYZWV8FGWN0Njbr/Rn7f/eWSQi1v7+HsUVwXgn8nWWlL64zKDkS0n8ZmQ3mlWOMuXOnR+7Nx/5tMO5AQ==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "dot-prop-4.2.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.0.tgz";
        sha512 = "tUMXrxlExSW6U2EXiiKGSBVdYgtV8qlHL+C10TsW4PURY/ic+eaysnSkwB4kA/mBlCyy/IKDJ+Lc3wbWeaXtuQ==";
      };
    };
    "electron-to-chromium-1.3.336" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.3.336";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.336.tgz";
        sha512 = "FtazvnXAizSVMxQNPqUcTv2UElY5r3uRPQwiU1Tyg/Yc2UFr+/3wqDoLIV9ES6ablW3IrCcR8uEK2ppxaNPWhw==";
      };
    };
    "entities-2.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.0.tgz";
        sha512 = "D9f7V0JSRwIxlRI2mjMqufDrRDnx8p+eEOz7aUM9SuvF8gsBzra0/6tbjl1m8eQHrZlYj6PxqE00hZ1SAIKPLw==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "es-abstract-1.17.2" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.2.tgz";
        sha512 = "YoKuru3Lyoy7yVTBSH2j7UxTqe/je3dWAruC0sHvZX1GNd5zX8SSLvQqEgO9b3Ex8IW+goFI9arEEsFIbulhOw==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "handlebars-4.7.2" = {
      name = "handlebars";
      packageName = "handlebars";
      version = "4.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/handlebars/-/handlebars-4.7.2.tgz";
        sha512 = "4PwqDL2laXtTWZghzzCtunQUTLbo31pcCJrd/B/9JP8XbhVzpS5ZXuKqlOzsd1rtcaLo4KqAn8nl8mkknS4MHw==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-symbols-1.0.1" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz";
        sha512 = "PLcsoqu++dmEIZB+6totNFKq/7Do+Z0u4oT0zKOJNl3lYK6vGwwu2hjHs+68OEZbTjiUE9bgOABXbP/GvrS0Kg==";
      };
    };
    "hex-color-regex-1.1.0" = {
      name = "hex-color-regex";
      packageName = "hex-color-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hex-color-regex/-/hex-color-regex-1.1.0.tgz";
        sha512 = "l9sfDFsuqtOqKDsQdqrMRk0U85RZc0RtOR9yPI7mRVOa4FsR/BVnZ0shmQRM96Ji99kYZP/7hn1cedc1+ApsTQ==";
      };
    };
    "highlight.js-9.17.1" = {
      name = "highlight.js";
      packageName = "highlight.js";
      version = "9.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/highlight.js/-/highlight.js-9.17.1.tgz";
        sha512 = "TA2/doAur5Ol8+iM3Ov7qy3jYcr/QiJ2eDTdRF4dfbjG7AaaB99J5G+zSl11ljbl6cIcahgPY6SKb3sC3EJ0fw==";
      };
    };
    "hsl-regex-1.0.0" = {
      name = "hsl-regex";
      packageName = "hsl-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsl-regex/-/hsl-regex-1.0.0.tgz";
        sha1 = "d49330c789ed819e276a4c0d272dffa30b18fe6e";
      };
    };
    "hsla-regex-1.0.0" = {
      name = "hsla-regex";
      packageName = "hsla-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsla-regex/-/hsla-regex-1.0.0.tgz";
        sha1 = "c1ce7a3168c8c6614033a4b5f7877f3b225f9c38";
      };
    };
    "html-comment-regex-1.1.2" = {
      name = "html-comment-regex";
      packageName = "html-comment-regex";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-comment-regex/-/html-comment-regex-1.1.2.tgz";
        sha512 = "P+M65QY2JQ5Y0G9KKdlDpo0zK+/OHptU5AaBwUfAIDJZk1MYf32Frm84EcOytfJE0t5JvkAnKlmjsXDnWzCJmQ==";
      };
    };
    "import-fresh-2.0.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-2.0.0.tgz";
        sha1 = "d81355c15612d386c61f9ddd3922d4304822a546";
      };
    };
    "indexes-of-1.0.1" = {
      name = "indexes-of";
      packageName = "indexes-of";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexes-of/-/indexes-of-1.0.1.tgz";
        sha1 = "f30f716c8e2bd346c7b67d3df3915566a7c05607";
      };
    };
    "is-absolute-url-2.1.0" = {
      name = "is-absolute-url";
      packageName = "is-absolute-url";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute-url/-/is-absolute-url-2.1.0.tgz";
        sha1 = "50530dfb84fcc9aa7dbe7852e83a37b93b9f2aa6";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-arrayish-0.3.2" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz";
        sha512 = "eVRqCvVlZbuw3GrM63ovNSNAeA1K16kaR/LRY/92w0zxQ5/1YzwblUX652i4Xs9RwAGjW9d9y6X88t8OaAJfWQ==";
      };
    };
    "is-callable-1.1.5" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.5.tgz";
        sha512 = "ESKv5sMCJB2jnHTWZ3O5itG+O128Hsus4K4Qh1h2/cgn2vbgnLSVqfV46AeJA9D5EeeLa9w81KUXMtn34zhX+Q==";
      };
    };
    "is-color-stop-1.1.0" = {
      name = "is-color-stop";
      packageName = "is-color-stop";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-color-stop/-/is-color-stop-1.1.0.tgz";
        sha1 = "cfff471aee4dd5c9e158598fbe12967b5cdad345";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-directory-0.3.1" = {
      name = "is-directory";
      packageName = "is-directory";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-directory/-/is-directory-0.3.1.tgz";
        sha1 = "61339b6f2475fc772fd9c9d83f5c8575dc154ae1";
      };
    };
    "is-obj-1.0.1" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz";
        sha1 = "3e4729ac1f5fde025cd7d83a896dab9f4f67db0f";
      };
    };
    "is-regex-1.0.5" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.5.tgz";
        sha512 = "vlKW17SNq44owv5AQR3Cq0bQPEb8+kF3UKZ2fiZNOWtztYE5i0CzCZxFDwO58qAOWtxdBRVO/V5Qin1wjCqFYQ==";
      };
    };
    "is-resolvable-1.1.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.1.0.tgz";
        sha512 = "qgDYXFSR5WvEfuS5dMj6oTMEbrrSaM0CrFk2Yiq/gXnBvD9pMa2jGXxyhGLfvhZpuMZe18CJpFxAt3CRs42NMg==";
      };
    };
    "is-svg-3.0.0" = {
      name = "is-svg";
      packageName = "is-svg";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-svg/-/is-svg-3.0.0.tgz";
        sha512 = "gi4iHK53LR2ujhLVVj+37Ykh9GLqYHX6JOVXbLAucaG/Cqw9xwdFOjDM2qeifLs1sF1npXXFvDu0r5HNgCMrzQ==";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "jquery-3.4.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.4.1.tgz";
        sha512 = "36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "js-yaml-3.13.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz";
        sha512 = "YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "lodash.memoize-4.1.2" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-4.1.2.tgz";
        sha1 = "bcc6c49a42a2840ed997f323eada5ecd182e0bfe";
      };
    };
    "lodash.uniq-4.5.0" = {
      name = "lodash.uniq";
      packageName = "lodash.uniq";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniq/-/lodash.uniq-4.5.0.tgz";
        sha1 = "d0225373aeb652adc1bc82e4945339a842754773";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "mdn-data-2.0.4" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.4.tgz";
        sha512 = "iV3XNKw06j5Q7mi6h+9vbx23Tv7JkjEVgKHW4pimwyDGWm0OIQntJJ+u1C6mg6mK1EaTv42XQ7w76yuzH7M2cA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "neo-async-2.6.1" = {
      name = "neo-async";
      packageName = "neo-async";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo-async/-/neo-async-2.6.1.tgz";
        sha512 = "iyam8fBuCUpWeKPGpaNMetEocMt364qkCsfL9JuhjXX6dRnguRVOfk2GZaDpPjcOKiiXCPINZC1GczQ7iTq3Zw==";
      };
    };
    "node-releases-1.1.45" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "1.1.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-1.1.45.tgz";
        sha512 = "cXvGSfhITKI8qsV116u2FTzH5EWZJfgG7d4cpqwF8I8+1tWpD6AsvvGRKq2onR0DNj1jfqsjkXZsm14JMS7Cyg==";
      };
    };
    "normalize-url-3.3.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-3.3.0.tgz";
        sha512 = "U+JJi7duF1o+u2pynbp2zXDW2/PADgC30f0GsHZtRh+HOcXHnw137TrNlyxxRvWW5fjKd3bcLHPxofWuCjaeZg==";
      };
    };
    "nth-check-1.0.2" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-1.0.2.tgz";
        sha512 = "WeBOdju8SnzPN5vTUJYxYUxLeXpCaVP5i5e0LF8fg7WORF2Wd7wFX/pk0tYZk7s8T+J7VLy0Da6J1+wCT0AtHg==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.7.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.7.0.tgz";
        sha512 = "a7pEHdh1xKIAgTySUGgLMx/xwDZskN1Ud6egYYN3EdRW4ZMPNEDUTF+hwy2LUC+Bl+SyLXANnwz/jyh/qutKUw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "exHJeq6kBKj58mqGyTQ9DFvrZC/eR6OwxzoM9YRoGBqrXYonaFyGiFMuc9VZrXf7DarreEwMpurG3dd+CNyW5w==";
      };
    };
    "object.getownpropertydescriptors-2.1.0" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.0.tgz";
        sha512 = "Z53Oah9A3TdLoblT7VKJaTDdXdT+lQO+cNpKVnya5JDe9uLvzu1YyY1yFDFrcxrlRgWrEFH0jJtD/IbuwjcEVg==";
      };
    };
    "object.values-1.1.1" = {
      name = "object.values";
      packageName = "object.values";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.values/-/object.values-1.1.1.tgz";
        sha512 = "WTa54g2K8iu0kmS/us18jEmdv1a4Wi//BZ/DTVYEcH0XhLM5NYdpDHja3gt57VrZLcNAO2WGA+KpWsDBaHt6eA==";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "parse-json-4.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-4.0.0.tgz";
        sha1 = "be35f5425be1f7f6c747184f98a788cb99477ee0";
      };
    };
    "popper.js-1.16.0" = {
      name = "popper.js";
      packageName = "popper.js";
      version = "1.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/popper.js/-/popper.js-1.16.0.tgz";
        sha512 = "+G+EkOPoE5S/zChTpmBSSDYmhXJ5PsW8eMhH8cP/CQHMFPBG/kC9Y5IIw6qNYgdJ+/COf0ddY2li28iHaZRSjw==";
      };
    };
    "postcss-7.0.26" = {
      name = "postcss";
      packageName = "postcss";
      version = "7.0.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-7.0.26.tgz";
        sha512 = "IY4oRjpXWYshuTDFxMVkJDtWIk2LhsTlu8bZnbEJA4+bYT16Lvpo8Qv6EvDumhYRgzjZl489pmsY3qVgJQ08nA==";
      };
    };
    "postcss-calc-7.0.1" = {
      name = "postcss-calc";
      packageName = "postcss-calc";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-calc/-/postcss-calc-7.0.1.tgz";
        sha512 = "oXqx0m6tb4N3JGdmeMSc/i91KppbYsFZKdH0xMOqK8V1rJlzrKlTdokz8ozUXLVejydRN6u2IddxpcijRj2FqQ==";
      };
    };
    "postcss-colormin-4.0.3" = {
      name = "postcss-colormin";
      packageName = "postcss-colormin";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-colormin/-/postcss-colormin-4.0.3.tgz";
        sha512 = "WyQFAdDZpExQh32j0U0feWisZ0dmOtPl44qYmJKkq9xFWY3p+4qnRzCHeNrkeRhwPHz9bQ3mo0/yVkaply0MNw==";
      };
    };
    "postcss-convert-values-4.0.1" = {
      name = "postcss-convert-values";
      packageName = "postcss-convert-values";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-convert-values/-/postcss-convert-values-4.0.1.tgz";
        sha512 = "Kisdo1y77KUC0Jmn0OXU/COOJbzM8cImvw1ZFsBgBgMgb1iL23Zs/LXRe3r+EZqM3vGYKdQ2YJVQ5VkJI+zEJQ==";
      };
    };
    "postcss-discard-comments-4.0.2" = {
      name = "postcss-discard-comments";
      packageName = "postcss-discard-comments";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-4.0.2.tgz";
        sha512 = "RJutN259iuRf3IW7GZyLM5Sw4GLTOH8FmsXBnv8Ab/Tc2k4SR4qbV4DNbyyY4+Sjo362SyDmW2DQ7lBSChrpkg==";
      };
    };
    "postcss-discard-duplicates-4.0.2" = {
      name = "postcss-discard-duplicates";
      packageName = "postcss-discard-duplicates";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-4.0.2.tgz";
        sha512 = "ZNQfR1gPNAiXZhgENFfEglF93pciw0WxMkJeVmw8eF+JZBbMD7jp6C67GqJAXVZP2BWbOztKfbsdmMp/k8c6oQ==";
      };
    };
    "postcss-discard-empty-4.0.1" = {
      name = "postcss-discard-empty";
      packageName = "postcss-discard-empty";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-4.0.1.tgz";
        sha512 = "B9miTzbznhDjTfjvipfHoqbWKwd0Mj+/fL5s1QOz06wufguil+Xheo4XpOnc4NqKYBCNqqEzgPv2aPBIJLox0w==";
      };
    };
    "postcss-discard-overridden-4.0.1" = {
      name = "postcss-discard-overridden";
      packageName = "postcss-discard-overridden";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-overridden/-/postcss-discard-overridden-4.0.1.tgz";
        sha512 = "IYY2bEDD7g1XM1IDEsUT4//iEYCxAmP5oDSFMVU/JVvT7gh+l4fmjciLqGgwjdWpQIdb0Che2VX00QObS5+cTg==";
      };
    };
    "postcss-merge-longhand-4.0.11" = {
      name = "postcss-merge-longhand";
      packageName = "postcss-merge-longhand";
      version = "4.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-longhand/-/postcss-merge-longhand-4.0.11.tgz";
        sha512 = "alx/zmoeXvJjp7L4mxEMjh8lxVlDFX1gqWHzaaQewwMZiVhLo42TEClKaeHbRf6J7j82ZOdTJ808RtN0ZOZwvw==";
      };
    };
    "postcss-merge-rules-4.0.3" = {
      name = "postcss-merge-rules";
      packageName = "postcss-merge-rules";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-rules/-/postcss-merge-rules-4.0.3.tgz";
        sha512 = "U7e3r1SbvYzO0Jr3UT/zKBVgYYyhAz0aitvGIYOYK5CPmkNih+WDSsS5tvPrJ8YMQYlEMvsZIiqmn7HdFUaeEQ==";
      };
    };
    "postcss-minify-font-values-4.0.2" = {
      name = "postcss-minify-font-values";
      packageName = "postcss-minify-font-values";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-font-values/-/postcss-minify-font-values-4.0.2.tgz";
        sha512 = "j85oO6OnRU9zPf04+PZv1LYIYOprWm6IA6zkXkrJXyRveDEuQggG6tvoy8ir8ZwjLxLuGfNkCZEQG7zan+Hbtg==";
      };
    };
    "postcss-minify-gradients-4.0.2" = {
      name = "postcss-minify-gradients";
      packageName = "postcss-minify-gradients";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-gradients/-/postcss-minify-gradients-4.0.2.tgz";
        sha512 = "qKPfwlONdcf/AndP1U8SJ/uzIJtowHlMaSioKzebAXSG4iJthlWC9iSWznQcX4f66gIWX44RSA841HTHj3wK+Q==";
      };
    };
    "postcss-minify-params-4.0.2" = {
      name = "postcss-minify-params";
      packageName = "postcss-minify-params";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-params/-/postcss-minify-params-4.0.2.tgz";
        sha512 = "G7eWyzEx0xL4/wiBBJxJOz48zAKV2WG3iZOqVhPet/9geefm/Px5uo1fzlHu+DOjT+m0Mmiz3jkQzVHe6wxAWg==";
      };
    };
    "postcss-minify-selectors-4.0.2" = {
      name = "postcss-minify-selectors";
      packageName = "postcss-minify-selectors";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-4.0.2.tgz";
        sha512 = "D5S1iViljXBj9kflQo4YutWnJmwm8VvIsU1GeXJGiG9j8CIg9zs4voPMdQDUmIxetUOh60VilsNzCiAFTOqu3g==";
      };
    };
    "postcss-normalize-charset-4.0.1" = {
      name = "postcss-normalize-charset";
      packageName = "postcss-normalize-charset";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-charset/-/postcss-normalize-charset-4.0.1.tgz";
        sha512 = "gMXCrrlWh6G27U0hF3vNvR3w8I1s2wOBILvA87iNXaPvSNo5uZAMYsZG7XjCUf1eVxuPfyL4TJ7++SGZLc9A3g==";
      };
    };
    "postcss-normalize-display-values-4.0.2" = {
      name = "postcss-normalize-display-values";
      packageName = "postcss-normalize-display-values";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-display-values/-/postcss-normalize-display-values-4.0.2.tgz";
        sha512 = "3F2jcsaMW7+VtRMAqf/3m4cPFhPD3EFRgNs18u+k3lTJJlVe7d0YPO+bnwqo2xg8YiRpDXJI2u8A0wqJxMsQuQ==";
      };
    };
    "postcss-normalize-positions-4.0.2" = {
      name = "postcss-normalize-positions";
      packageName = "postcss-normalize-positions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-positions/-/postcss-normalize-positions-4.0.2.tgz";
        sha512 = "Dlf3/9AxpxE+NF1fJxYDeggi5WwV35MXGFnnoccP/9qDtFrTArZ0D0R+iKcg5WsUd8nUYMIl8yXDCtcrT8JrdA==";
      };
    };
    "postcss-normalize-repeat-style-4.0.2" = {
      name = "postcss-normalize-repeat-style";
      packageName = "postcss-normalize-repeat-style";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-repeat-style/-/postcss-normalize-repeat-style-4.0.2.tgz";
        sha512 = "qvigdYYMpSuoFs3Is/f5nHdRLJN/ITA7huIoCyqqENJe9PvPmLhNLMu7QTjPdtnVf6OcYYO5SHonx4+fbJE1+Q==";
      };
    };
    "postcss-normalize-string-4.0.2" = {
      name = "postcss-normalize-string";
      packageName = "postcss-normalize-string";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-string/-/postcss-normalize-string-4.0.2.tgz";
        sha512 = "RrERod97Dnwqq49WNz8qo66ps0swYZDSb6rM57kN2J+aoyEAJfZ6bMx0sx/F9TIEX0xthPGCmeyiam/jXif0eA==";
      };
    };
    "postcss-normalize-timing-functions-4.0.2" = {
      name = "postcss-normalize-timing-functions";
      packageName = "postcss-normalize-timing-functions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-timing-functions/-/postcss-normalize-timing-functions-4.0.2.tgz";
        sha512 = "acwJY95edP762e++00Ehq9L4sZCEcOPyaHwoaFOhIwWCDfik6YvqsYNxckee65JHLKzuNSSmAdxwD2Cud1Z54A==";
      };
    };
    "postcss-normalize-unicode-4.0.1" = {
      name = "postcss-normalize-unicode";
      packageName = "postcss-normalize-unicode";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-unicode/-/postcss-normalize-unicode-4.0.1.tgz";
        sha512 = "od18Uq2wCYn+vZ/qCOeutvHjB5jm57ToxRaMeNuf0nWVHaP9Hua56QyMF6fs/4FSUnVIw0CBPsU0K4LnBPwYwg==";
      };
    };
    "postcss-normalize-url-4.0.1" = {
      name = "postcss-normalize-url";
      packageName = "postcss-normalize-url";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-4.0.1.tgz";
        sha512 = "p5oVaF4+IHwu7VpMan/SSpmpYxcJMtkGppYf0VbdH5B6hN8YNmVyJLuY9FmLQTzY3fag5ESUUHDqM+heid0UVA==";
      };
    };
    "postcss-normalize-whitespace-4.0.2" = {
      name = "postcss-normalize-whitespace";
      packageName = "postcss-normalize-whitespace";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-whitespace/-/postcss-normalize-whitespace-4.0.2.tgz";
        sha512 = "tO8QIgrsI3p95r8fyqKV+ufKlSHh9hMJqACqbv2XknufqEDhDvbguXGBBqxw9nsQoXWf0qOqppziKJKHMD4GtA==";
      };
    };
    "postcss-ordered-values-4.1.2" = {
      name = "postcss-ordered-values";
      packageName = "postcss-ordered-values";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-4.1.2.tgz";
        sha512 = "2fCObh5UanxvSxeXrtLtlwVThBvHn6MQcu4ksNT2tsaV2Fg76R2CV98W7wNSlX+5/pFwEyaDwKLLoEV7uRybAw==";
      };
    };
    "postcss-reduce-initial-4.0.3" = {
      name = "postcss-reduce-initial";
      packageName = "postcss-reduce-initial";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-initial/-/postcss-reduce-initial-4.0.3.tgz";
        sha512 = "gKWmR5aUulSjbzOfD9AlJiHCGH6AEVLaM0AV+aSioxUDd16qXP1PCh8d1/BGVvpdWn8k/HiK7n6TjeoXN1F7DA==";
      };
    };
    "postcss-reduce-transforms-4.0.2" = {
      name = "postcss-reduce-transforms";
      packageName = "postcss-reduce-transforms";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-transforms/-/postcss-reduce-transforms-4.0.2.tgz";
        sha512 = "EEVig1Q2QJ4ELpJXMZR8Vt5DQx8/mo+dGWSR7vWXqcob2gQLyQGsionYcGKATXvQzMPn6DSN1vTN7yFximdIAg==";
      };
    };
    "postcss-selector-parser-3.1.1" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-3.1.1.tgz";
        sha1 = "4f875f4afb0c96573d5cf4d74011aee250a7e865";
      };
    };
    "postcss-selector-parser-5.0.0" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-5.0.0.tgz";
        sha512 = "w+zLE5Jhg6Liz8+rQOWEAwtwkyqpfnmsinXjXg6cY7YIONZZtgvE0v2O0uhQBs0peNomOJwWRKt6JBfTdTd3OQ==";
      };
    };
    "postcss-svgo-4.0.2" = {
      name = "postcss-svgo";
      packageName = "postcss-svgo";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-svgo/-/postcss-svgo-4.0.2.tgz";
        sha512 = "C6wyjo3VwFm0QgBy+Fu7gCYOkCmgmClghO+pjcxvrcBKtiKt0uCF+hvbMO1fyv5BMImRK90SMb+dwUnfbGd+jw==";
      };
    };
    "postcss-unique-selectors-4.0.1" = {
      name = "postcss-unique-selectors";
      packageName = "postcss-unique-selectors";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-4.0.1.tgz";
        sha512 = "+JanVaryLo9QwZjKrmJgkI4Fn8SBgRO6WXQBJi7KiAVPlmxikB5Jzc4EvXMT2H0/m0RjrVVm9rGNhZddm/8Spg==";
      };
    };
    "postcss-value-parser-3.3.1" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-3.3.1.tgz";
        sha512 = "pISE66AbVkp4fDQ7VHBwRNXzAAKJjw4Vw7nWI/+Q3vuly7SNfgYXvm6i5IgFylHGK5sP/xHAbB7N49OS4gWNyQ==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "q-1.5.1" = {
      name = "q";
      packageName = "q";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.5.1.tgz";
        sha1 = "7e32f75b41381291d04611f1bf14109ac00651d7";
      };
    };
    "react-16.12.0" = {
      name = "react";
      packageName = "react";
      version = "16.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.12.0.tgz";
        sha512 = "fglqy3k5E+81pA8s+7K0/T3DBCF0ZDOher1elBFzF7O6arXJgzyu/FW+COxFvAWXJoJN9KIZbT2LXlukwphYTA==";
      };
    };
    "react-dom-16.12.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.12.0.tgz";
        sha512 = "LMxFfAGrcS3kETtQaCkTKjMiifahaMySFDn71fZUNpPHZQEzmk/GiAeIT8JSOrHB23fnuCOMruL2a8NYlw+8Gw==";
      };
    };
    "react-is-16.12.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.12.0.tgz";
        sha512 = "rPCkf/mWBtKc97aLL9/txD8DZdemK0vkA3JMLShjlJB3Pj3s+lpf1KaBzMfQrAmhMQB0n1cU/SUGgKKBCe837Q==";
      };
    };
    "resolve-from-3.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-3.0.0.tgz";
        sha1 = "b22c7af7d9d6881bc8b6e653335eebcb0a188748";
      };
    };
    "rgb-regex-1.0.1" = {
      name = "rgb-regex";
      packageName = "rgb-regex";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgb-regex/-/rgb-regex-1.0.1.tgz";
        sha1 = "c0e0d6882df0e23be254a475e8edd41915feaeb1";
      };
    };
    "rgba-regex-1.0.0" = {
      name = "rgba-regex";
      packageName = "rgba-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgba-regex/-/rgba-regex-1.0.0.tgz";
        sha1 = "43374e2e2ca0968b0ef1523460b7d730ff22eeb3";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "scheduler-0.18.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.18.0.tgz";
        sha512 = "agTSHR1Nbfi6ulI0kYNK0203joW2Y5W4po4l+v03tOoiJKpTBbxpNhWDvqc/4IcOw+KLmSiQLTasZ4cab2/UWQ==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "simple-swizzle-0.2.2" = {
      name = "simple-swizzle";
      packageName = "simple-swizzle";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz";
        sha1 = "a4da6b635ffcccca33f70d17cb92592de95e557a";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "stable-0.1.8" = {
      name = "stable";
      packageName = "stable";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/stable/-/stable-0.1.8.tgz";
        sha512 = "ji9qxRnOVfcuLDySj9qzhGSEFVobyt1kIOSkj1qZzYLzq7Tos/oUUWvotUPQLlrsidqsK6tBH89Bc9kL5zHA6w==";
      };
    };
    "string.prototype.trimleft-2.1.1" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.1.tgz";
        sha512 = "iu2AGd3PuP5Rp7x2kEZCrB2Nf41ehzh+goo8TV7z8/XDBbsvc6HQIlUl9RjkZ4oyrW1XM5UwlGl1oVEaDjg6Ag==";
      };
    };
    "string.prototype.trimright-2.1.1" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.1.tgz";
        sha512 = "qFvWL3/+QIgZXVmJBfpHmxLB7xsUXz6HsUmP8+5dRaC3Q7oKUv9Vo6aMCRZC1smrtyECFsIT30PqBJ1gTjAs+g==";
      };
    };
    "stylehacks-4.0.3" = {
      name = "stylehacks";
      packageName = "stylehacks";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylehacks/-/stylehacks-4.0.3.tgz";
        sha512 = "7GlLk9JwlElY4Y6a/rmbH2MhVlTyVmiJd1PfTCqFaIBEGMYNsrO/v3SeGTdhBThLg4Z+NbOk/qFMwCa+J+3p/g==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "svgo-1.3.2" = {
      name = "svgo";
      packageName = "svgo";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgo/-/svgo-1.3.2.tgz";
        sha512 = "yhy/sQYxR5BkC98CY7o31VGsg014AKLEPxdfhora76l36hD9Rdy5NZA/Ocn6yayNPgSamYdtX2rFJdcv07AYVw==";
      };
    };
    "timsort-0.3.0" = {
      name = "timsort";
      packageName = "timsort";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timsort/-/timsort-0.3.0.tgz";
        sha1 = "405411a8e7e6339fe64db9a234de11dc31e02bd4";
      };
    };
    "uglify-js-3.7.5" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "3.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.7.5.tgz";
        sha512 = "GFZ3EXRptKGvb/C1Sq6nO1iI7AGcjyqmIyOw0DrD0675e+NNbGO72xmMM2iEBdFbxaTLo70NbjM/Wy54uZIlsg==";
      };
    };
    "uniq-1.0.1" = {
      name = "uniq";
      packageName = "uniq";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniq/-/uniq-1.0.1.tgz";
        sha1 = "b31c5ae8254844a3a8281541ce2b04b865a734ff";
      };
    };
    "uniqs-2.0.0" = {
      name = "uniqs";
      packageName = "uniqs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz";
        sha1 = "ffede4b36b25290696e6e165d4a59edb998e6b02";
      };
    };
    "unquote-1.1.1" = {
      name = "unquote";
      packageName = "unquote";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unquote/-/unquote-1.1.1.tgz";
        sha1 = "8fded7324ec6e88a0ff8b905e7c098cdc086d544";
      };
    };
    "util.promisify-1.0.1" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.1.tgz";
        sha512 = "g9JpC/3He3bm38zsLupWryXHoEcS22YHthuPQSJdMy6KNrzIRzWqcsHzD/WUnqe45whVou4VIsPew37DoXWNrA==";
      };
    };
    "vendors-1.0.3" = {
      name = "vendors";
      packageName = "vendors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vendors/-/vendors-1.0.3.tgz";
        sha512 = "fOi47nsJP5Wqefa43kyWSg80qF+Q3XA6MUkgi7Hp1HQaKDQW4cQrK2D0P7mmbFtsV1N89am55Yru/nyEwRubcw==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
  };
  args = {
    name = "webapp";
    packageName = "webapp";
    version = "0.0.0";
    src = ./.;
    dependencies = [
      sources."@fortawesome/fontawesome-free-5.12.0"
      sources."@types/q-1.5.2"
      sources."alphanum-sort-1.0.2"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."boolbase-1.0.0"
      sources."bootstrap-4.4.1"
      sources."browserslist-4.8.3"
      sources."caller-callsite-2.0.0"
      sources."caller-path-2.0.0"
      sources."callsites-2.0.0"
      sources."caniuse-api-3.0.0"
      sources."caniuse-lite-1.0.30001021"
      sources."chalk-2.4.2"
      sources."coa-2.0.2"
      sources."color-3.1.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."color-string-1.5.3"
      sources."commander-2.20.3"
      sources."cosmiconfig-5.2.1"
      sources."css-color-names-0.0.4"
      sources."css-declaration-sorter-4.0.1"
      sources."css-select-2.1.0"
      sources."css-select-base-adapter-0.1.1"
      sources."css-tree-1.0.0-alpha.37"
      sources."css-unit-converter-1.1.1"
      sources."css-what-3.2.1"
      sources."cssesc-2.0.0"
      sources."cssnano-4.1.10"
      sources."cssnano-preset-default-4.0.7"
      sources."cssnano-util-get-arguments-4.0.0"
      sources."cssnano-util-get-match-4.0.0"
      sources."cssnano-util-raw-cache-4.0.1"
      sources."cssnano-util-same-parent-4.0.1"
      sources."csso-4.0.2"
      sources."define-properties-1.1.3"
      (sources."dom-serializer-0.2.2" // {
        dependencies = [
          sources."domelementtype-2.0.1"
        ];
      })
      sources."domelementtype-1.3.1"
      sources."domutils-1.7.0"
      sources."dot-prop-4.2.0"
      sources."electron-to-chromium-1.3.336"
      sources."entities-2.0.0"
      sources."error-ex-1.3.2"
      sources."es-abstract-1.17.2"
      sources."es-to-primitive-1.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."function-bind-1.1.1"
      sources."handlebars-4.7.2"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."has-symbols-1.0.1"
      sources."hex-color-regex-1.1.0"
      sources."highlight.js-9.17.1"
      sources."hsl-regex-1.0.0"
      sources."hsla-regex-1.0.0"
      sources."html-comment-regex-1.1.2"
      sources."import-fresh-2.0.0"
      sources."indexes-of-1.0.1"
      sources."is-absolute-url-2.1.0"
      sources."is-arrayish-0.2.1"
      sources."is-callable-1.1.5"
      sources."is-color-stop-1.1.0"
      sources."is-date-object-1.0.2"
      sources."is-directory-0.3.1"
      sources."is-obj-1.0.1"
      sources."is-regex-1.0.5"
      sources."is-resolvable-1.1.0"
      sources."is-svg-3.0.0"
      sources."is-symbol-1.0.3"
      sources."jquery-3.4.1"
      sources."js-tokens-4.0.0"
      sources."js-yaml-3.13.1"
      sources."json-parse-better-errors-1.0.2"
      sources."lodash.memoize-4.1.2"
      sources."lodash.uniq-4.5.0"
      sources."loose-envify-1.4.0"
      sources."mdn-data-2.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."neo-async-2.6.1"
      sources."node-releases-1.1.45"
      sources."normalize-url-3.3.0"
      sources."nth-check-1.0.2"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.7.0"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."object.getownpropertydescriptors-2.1.0"
      sources."object.values-1.1.1"
      sources."optimist-0.6.1"
      sources."parse-json-4.0.0"
      sources."popper.js-1.16.0"
      (sources."postcss-7.0.26" // {
        dependencies = [
          sources."supports-color-6.1.0"
        ];
      })
      sources."postcss-calc-7.0.1"
      sources."postcss-colormin-4.0.3"
      sources."postcss-convert-values-4.0.1"
      sources."postcss-discard-comments-4.0.2"
      sources."postcss-discard-duplicates-4.0.2"
      sources."postcss-discard-empty-4.0.1"
      sources."postcss-discard-overridden-4.0.1"
      sources."postcss-merge-longhand-4.0.11"
      (sources."postcss-merge-rules-4.0.3" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.1"
        ];
      })
      sources."postcss-minify-font-values-4.0.2"
      sources."postcss-minify-gradients-4.0.2"
      sources."postcss-minify-params-4.0.2"
      (sources."postcss-minify-selectors-4.0.2" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.1"
        ];
      })
      sources."postcss-normalize-charset-4.0.1"
      sources."postcss-normalize-display-values-4.0.2"
      sources."postcss-normalize-positions-4.0.2"
      sources."postcss-normalize-repeat-style-4.0.2"
      sources."postcss-normalize-string-4.0.2"
      sources."postcss-normalize-timing-functions-4.0.2"
      sources."postcss-normalize-unicode-4.0.1"
      sources."postcss-normalize-url-4.0.1"
      sources."postcss-normalize-whitespace-4.0.2"
      sources."postcss-ordered-values-4.1.2"
      sources."postcss-reduce-initial-4.0.3"
      sources."postcss-reduce-transforms-4.0.2"
      sources."postcss-selector-parser-5.0.0"
      sources."postcss-svgo-4.0.2"
      sources."postcss-unique-selectors-4.0.1"
      sources."postcss-value-parser-3.3.1"
      sources."prop-types-15.7.2"
      sources."q-1.5.1"
      sources."react-16.12.0"
      sources."react-dom-16.12.0"
      sources."react-is-16.12.0"
      sources."resolve-from-3.0.0"
      sources."rgb-regex-1.0.1"
      sources."rgba-regex-1.0.0"
      sources."sax-1.2.4"
      sources."scheduler-0.18.0"
      sources."semver-6.3.0"
      (sources."simple-swizzle-0.2.2" // {
        dependencies = [
          sources."is-arrayish-0.3.2"
        ];
      })
      sources."source-map-0.6.1"
      sources."sprintf-js-1.0.3"
      sources."stable-0.1.8"
      sources."string.prototype.trimleft-2.1.1"
      sources."string.prototype.trimright-2.1.1"
      (sources."stylehacks-4.0.3" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.1"
        ];
      })
      sources."supports-color-5.5.0"
      sources."svgo-1.3.2"
      sources."timsort-0.3.0"
      sources."uglify-js-3.7.5"
      sources."uniq-1.0.1"
      sources."uniqs-2.0.0"
      sources."unquote-1.1.1"
      sources."util.promisify-1.0.1"
      sources."vendors-1.0.3"
      sources."wordwrap-0.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}