name: ci

on: [push]

jobs:
  build:
    name: test / build / publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: zfs-snap-diff
          attributes: bindata
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: test
        run: |
          echo "testing backend code"
          for PKG in $(\ls -1d pkg/*); do
            go test ./$PKG
          done

          echo "testing frontend code"
          nix-shell --run 'cd webapp; spago test'


      - name: build for all platforms
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          set -x
          VERSION=$(git describe --always)
          for GOOS in linux freebsd darwin solaris; do
            echo "BUILD: $GOOS"
            BUILD=$(nix-build --no-out-link --no-build-output -A zfs-snap-diff --argstr goos $GOOS)
            cp -fv $BUILD/bin/zfs-snap-diff .
            cp -fv $BUILD/bin/zsd .
            cp -fv $BUILD/share/LICENSE .

            ARCHIVE=zfs-snap-diff-$GOOS-$VERSION.tgz
            tar cvfz $ARCHIVE zfs-snap-diff zsd LICENSE
          done

      - name: upload assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: zfs-snap-diff*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
