# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "react-is-16.11.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.11.0.tgz";
        sha512 = "gbBVYR2p8mnriqAwWx9LbuUrShnAuSCNnuPGyc7GJrMVQtPDAh8iLpv7FRuMPFb56KkaVZIYSz1PrjI9q0QPCw==";
      };
    };
    "scheduler-0.17.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.17.0.tgz";
        sha512 = "7rro8Io3tnCPuY4la/NuI5F2yfESpnfZyT6TtkXnSWVkcu0BCDJ+8gk5ozUaFaxpIyNuWAPXrH0yFcSi28fnDA==";
      };
    };
  };
in
{
  react = nodeEnv.buildNodePackage {
    name = "react";
    packageName = "react";
    version = "16.11.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/react/-/react-16.11.0.tgz";
      sha512 = "M5Y8yITaLmU0ynd0r1Yvfq98Rmll6q8AxaEe88c8e7LxO8fZ2cNgmFt0aGAS9wzf1Ao32NKXtCl+/tVVtkxq6g==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-is-16.11.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React is a JavaScript library for building user interfaces.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  react-dom = nodeEnv.buildNodePackage {
    name = "react-dom";
    packageName = "react-dom";
    version = "16.11.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/react-dom/-/react-dom-16.11.0.tgz";
      sha512 = "nrRyIUE1e7j8PaXSPtyRKtz+2y9ubW/ghNgqKFHHAHaeP0fpF5uXR+sq8IMRHC+ZUxw7W9NyCDTBtwWxvkb0iA==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-is-16.11.0"
      sources."scheduler-0.17.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React package for working with the DOM.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  octicons = nodeEnv.buildNodePackage {
    name = "octicons";
    packageName = "octicons";
    version = "8.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/octicons/-/octicons-8.5.0.tgz";
      sha512 = "l4GCHwBvStuwVfIuqUx/ktFJQJdCqLnd0bi2dvYZzkza6wj9EUksfMUlTqyVMULbPIvRTXxOqn/W07fsMu1bXA==";
    };
    dependencies = [
      sources."object-assign-4.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A scalable set of icons handcrafted with <3 by GitHub.";
      homepage = https://octicons.github.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "highlight.js" = nodeEnv.buildNodePackage {
    name = "highlight.js";
    packageName = "highlight.js";
    version = "9.16.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/highlight.js/-/highlight.js-9.16.2.tgz";
      sha512 = "feMUrVLZvjy0oC7FVJQcSQRqbBq9kwqnYE4+Kj9ZjbHh3g+BisiPgF49NyQbVLNdrL/qqZr3Ca9yOKwgn2i/tw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Syntax highlighting with language autodetection.";
      homepage = https://highlightjs.org/;
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
  };
  bootstrap = nodeEnv.buildNodePackage {
    name = "bootstrap";
    packageName = "bootstrap";
    version = "4.3.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/bootstrap/-/bootstrap-4.3.1.tgz";
      sha512 = "rXqOmH1VilAt2DyPzluTi2blhk17bO7ef+zLLPlWvG494pDxcM234pJ8wTc/6R40UWizAIIMgxjvxZg5kmsbag==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The most popular front-end framework for developing responsive, mobile first projects on the web.";
      homepage = https://getbootstrap.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}